### ISSUE TITLE
Grid needs to be anchored

### ISSUE THREAD

**Issue by daryllabar** [bonomo1/XRMSolutionDependencyChecker#5]
The grid should be anchored to all four sides of the form.
![image](https://user-images.githubusercontent.com/9728423/136612621-0b70dc6b-17e9-477b-b17d-0b7170969bd5.png)

**Comment by bonomo1** [comment]
Thanks @daryllabar.

**Comment by bonomo1** [comment]
This is resolved in the latest version that was moved under the Corterra Solutions repository here: https://github.com/CorterraSolutions/SolutionDependencyChecker
